version: '3.8'

services:
  redis-proxy:
    build: .
    environment:
      - PROXY_HOST=0.0.0.0
      - PROXY_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_EXPIRY_TIME=300
      - CACHE_CAPACITY=1000
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

# services:
#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"

#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     depends_on:
#       - redis
#     environment:
#       - REDIS_URL=redis://redis:6379/0
